### ISSUE TITLE
Cabinet photos not centered

### ISSUE THREAD

**Issue by LordFarquaadtheCreator** [BYTE-Club-CCNY/byte#17]
The cabinet photos are slightly off center from the div - looks misaligned. 
Could use centering.

<img width="1206" alt="Screenshot 2024-05-28 at 12 12 15 PM" src="https://github.com/BYTE-Club-CCNY/byte/assets/81727522/87dd6a16-3a9b-436f-ba79-ca4e3d4b9a1e">

**Comment by jaynopponep** [comment]
![image](https://github.com/BYTE-Club-CCNY/byte/assets/34385282/ea3a6ec2-4068-494c-8ecd-c768f6cd8e72)
thoughts?
