### ISSUE TITLE
Photos not showing on mobile

### ISSUE THREAD

**Issue by LordFarquaadtheCreator** [BYTE-Club-CCNY/byte#18]
Cabinet photos won't show on mobile

**Comment by jaynopponep** [comment]
![image](https://github.com/BYTE-Club-CCNY/byte/assets/34385282/b8c6385e-8805-45b6-8e6b-431ee3fe9248)

Able to have it show, available in eboard-img-center branch. Let me know any adjustments needed. I tried to center the image more but nothing is really working if someone else can investigate that maybe im overlooking something
