### ISSUE TITLE
Dark mode toggle

### ISSUE THREAD

**Issue by LordFarquaadtheCreator** [BYTE-Club-CCNY/byte#21]
There should a toggle to switch between dark and light mode

**Comment by LordFarquaadtheCreator** [comment]
open to dismissing this since darkmode is toggled on user's system settings

**Comment by LordFarquaadtheCreator** [comment]
> open to dismissing this since darkmode is toggled on user's system settings

@jaynopponep thoughts?

**Comment by jaynopponep** [comment]
i was still open to finding a way to implement this since it would be nice, still need to do abit more research

**Comment by LordFarquaadtheCreator** [comment]
> i was still open to finding a way to implement this since it would be nice, still need to do abit more research @LordFarquaadtheCreator

late reply but yeah, then look into it
