### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by LordFarquaadtheCreator** [BYTE-Club-CCNY/byte#30]
Website broken on firefox - seems to be aceternity's fault. 
High priority!

**Comment by Evandabest** [comment]
## The problem
The component library seems to be incompatible with older versions of NextJs for Firefox specifically. Aceternity came out a few months ago while NextJs 13 came out almost two years ago. Below I have attached a gif of one of the components fully working on Firefox using NextJs 14, compared to the NextJs 13 version. 

![Kapture 2024-06-05 at 09 56 59](https://github.com/BYTE-Club-CCNY/byte/assets/145516605/84a1aeb3-4379-4d64-86ca-475ee428ba8b)

## Solution
We have to upgrade to NextJs 14 for the component to properly render. However, upgrading to NextJs 14 will come with some trade offs. We will not be able to use the Cypress testing framework and we have to carefully review our code. Simply running
```bash
npm i next@latest react@latest react-dom@latest eslint-config-next@latest
```
won't work as expected. The components still seem to be static after trying this on a local copy as seen below.

![Kapture 2024-06-05 at 11 02 01](https://github.com/BYTE-Club-CCNY/byte/assets/145516605/90a77f6a-d16e-4b8d-a829-94aafef2a554)

**Comment by LordFarquaadtheCreator** [comment]
Installed using bun, works there. Tried running with node - works as well. Maybe its an npm issue? Regardless, I'll try deploying this new version to amplify and see how it runs.

**Comment by LordFarquaadtheCreator** [comment]
Migrated, but didnt resolve

**Comment by LordFarquaadtheCreator** [comment]
fixed in main - it was a tailwind css issue that wasnt fully supported on firefox
